version: '3'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Orion123
      POSTGRES_DB: keycloak_db
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  keycloak3:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: Orion123
      KEYCLOAK_USER: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:      
      - "8484:8080"
    volumes:
      - ./themes/rtl:/opt/jboss/keycloak/themes/rtl
      - ./img.png:/opt/jboss/keycloak/themes/keycloak/login/resources/img/keycloak-bg.png
    depends_on:
      - postgres
