version: '3'

services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lolkek123
      POSTGRES_DB: postgres

  keycloak3:
    image: testkk01:latest
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: Lolkek123
      KC_HOSTNAME: keycloak3
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KEYCLOAK_ADMIN: rtlkcadm
      KEYCLOAK_ADMIN_PASSWORD: Lolkek123
      KEYCLOAK_LOGLEVEL: DEBUG
      KC_HTTP_ENABLED: true
    ports:
      - "8484:8080"
    depends_on:
      - postgres