services:
  keycloak_db:
    image: postgres:17
    expose:
      - 5432
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kcdb
      POSTGRES_USER: kcdbadm
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak-db-volume:/var/lib/postgresql/data
    networks:
      - docker-bridge-network

  keycloak:
    image: ihavelapki/kc:latest
    ports:
      - "8080:8080"
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: kcdb
      KC_DB_USERNAME: kcdbadm
      KC_DB_URL: "jdbc:postgresql://keycloak_db:5432/kcdb"
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${MASTER_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${MASTER_PASSWORD}
      KC_LOG_LEVEL: "ERROR"
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HTTPS_CERTIFICATE_FILE: "/opt/rtl/ssl/tls.crt"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/rtl/ssl/tls.key"
      KC_PROXY_HEADERS: "xforwarded"
      KC_PROXY_PROTOCOL_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
    command: start -v
    depends_on:
      - keycloak_db
    networks:
      - docker-bridge-network

volumes:
  keycloak-db-volume:
    external: true

networks:
  docker-bridge-network:
    external: true